name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip .[graph,dev]
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py311 .
        continue-on-error: true
      - name: Test with pytest and coverage
        run: |
          pytest --cov=pyontronics --cov-report=term-missing --cov-report=xml
